"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

"""


def problem002():
    sum = 2
    previous2 = 1
    previous = 2
    while previous < 4e6:
        temp1 = previous2
        temp2 = previous
        previous2 = previous
        previous = temp1 + temp2
        if previous % 2 == 0 and previous < 4e6:
            sum = sum + previous
    print(sum)


if __name__ == "__main__":
    problem002()
